{% set name = "youtube-search-python" %}
{% set version = "1.6.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/youtube-search-python-{{ version }}.tar.gz
  sha256: 4568d1d769ecd7eb4bb8365f04eec6e364c5f70eec7b3765f543daebb135fcf5

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - httpx >=0.14.2
    - python >={{ python_min }}
    - yt-dlp

test:
  imports:
    - youtubesearchpython
    - youtubesearchpython.__future__
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/alexmercerind/youtube-search-python
  summary: Search for YouTube videos, channels & playlists & get video information using link WITHOUT YouTube Data API v3
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/alexmercerind/youtube-search-python

extra:
  recipe-maintainers:
    - HeavyTony2
